### ISSUE TITLE
Regression for HMTL files with no Javascript

### ISSUE THREAD

**Issue by kevincox** [assetgraph/assetgraph-rollup#2]
It seems that 0.0.4 (I haven't tested 2 and 3) fails for HTML files with no scripts.

This is inconvenient because I was just selecting all HTML files without regard for if they had scripts or not. Getting only the files with scripts is much more fuss.

```
Error: You must supply options.input to rollup
    at Graph.generateModuleGraph (/builds/kevincox/gridfinder/node_modules/rollup/dist/shared/rollup.js:18867:19)
    at async Graph.build (/builds/kevincox/gridfinder/node_modules/rollup/dist/shared/rollup.js:18831:9)
    at async rollupInternal (/builds/kevincox/gridfinder/node_modules/rollup/dist/shared/rollup.js:19883:9)
    at async bundleRollup (/builds/kevincox/gridfinder/node_modules/assetgraph-rollup/lib/assetgraph-rollup.js:62:18)
```

Code triggering the issue https://gitlab.com/kevincox/gridfinder/-/blob/7289a0b73a8a6575da800c79dab1aae8a89bb5a2/build.mjs#L22-24 (I have verified that it is the faq.html file which is failing).

Full build log: https://gitlab.com/kevincox/gridfinder/-/jobs/849206218

**Comment by papandreou** [comment]
Thanks! Fixed in 0.1.0.
